project:
  type: website
  output-dir: docs
website:
  title: "Ava Toomey-Cordeiro"
  navbar: 
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: edandexperience.qmd
        text: Education and Experience
      

format:
  html:
    theme: 
      - morph 
      - styles.scss
    mainfont: Raleway
    toc: true
    page-layout: full

editor: visual

